### ISSUE TITLE
Error with AnKindlePlus when there's no internet

### ISSUE THREAD

**Issue by Arthaey** [upday7/AnKindle#6]
If I paid for AnKindlePlus already but at some point don't have an internet connection, I see this error when starting Anki:

```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/progress.pyc", line 69, in handler
  File "aqt/main.pyc", line 110, in setupProfile
  File "aqt/main.pyc", line 244, in loadProfile
  File "anki/hooks.pyc", line 26, in runHook
  File "/Users/cmrodgers/Library/Application Support/Anki2/addons/AnKindle/__init__.py", line 181, in start
    rr = AnKindleAddon()
  File "/Users/cmrodgers/Library/Application Support/Anki2/addons/AnKindle/__init__.py", line 74, in __init__
    if self.ext_available and not self.ext_unlocked:
  File "/Users/cmrodgers/Library/Application Support/Anki2/addons/AnKindle/__init__.py", line 128, in ext_unlocked
    return AnKindlePlus.KuangKuang.Unlocked()
  File "AnKindlePlus.py", line 1521, in AnKindleExt.AnKindlePlus.KuangKuang.Unlocked
  File "AnKindlePlus.py", line 1839, in AnKindleExt.AnKindlePlus.SNReg.cls_register
  File "httplib.pyc", line 973, in request
  File "httplib.pyc", line 1007, in _send_request
  File "httplib.pyc", line 969, in endheaders
  File "httplib.pyc", line 829, in _send_output
  File "aqt/sync.pyc", line 441, in _incrementalSend
  File "httplib.pyc", line 772, in connect
  File "socket.pyc", line 553, in create_connection
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by Arthaey** [comment]
Thanks for merging #7 to include my fix! :)
